apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-fixed
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
  volumes:
  - name: safe-storage
    emptyDir: {}